openapi: 3.0.0
info:
  title: Music Playlist Service
  description: "This is the API definition for the Music Playlist Service."
  version: 1.0.0

servers:
  - url: http://localhost:3000

tags:
  - name: Booklists
    description: Create, view, and update booklists

  - name: Book
    description: View and add songs to booklists

paths:

  /booklists/search:
    get:
      tags:
        - Booklists
      parameters:
        - name: q
          in: query
          description: Search term (name or tag)
          required: true
          schema:
            type: array
            items:
              type: string
      summary: Search for a booklist (SearchBooklistsLambda)
      responses:
        "200":
          description: A booklist object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  customerId:
                    type: string
                  bookCount:
                    type: integer
                  tags:
                    type: array
                    items:
                      type: string
                  asins:
                    type: array
                    items:
                      type: string

  /booklists:
    post:
      tags:
        - Booklists
      summary: Create a new booklist (CreateBooklistLambda)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                customerId:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: A booklist object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  customerId:
                    type: string
                  bookCount:
                    type: integer
                  tags:
                    type: array
                    items:
                      type: string
                  asins:
                    type: array
                    items:
                      type: string

  /books/{currentlyReading} {id}:
    get:
      tags:
        - Booklists
        - Books
      summary: Get all books that are being read (GetCurrentlyReadingLambda)
      parameters:
        - name: currentlyReading
          in: path
          description: boolean of the currentlyReading value to create a list from
          required: true
          schema:
            type: boolean
        - name: id
          in: path
          description: id of the playlist to check, if blank will return all currently reading
          required: false
          schema:
            type: string
      responses:
        "200":
          description: BooklistResponse
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  customerId:
                    type: string
                  bookCount:
                    type: integer
                  tags:
                    type: array
                    items:
                      type: string
        "500":
          description: "Invalid input parameters"

  /booklists/{id}:
    get:
      tags:
        - Booklists
      summary: Get an existing booklist (GetBooklistLambda)
      parameters:
        - name: id
          in: path
          description: ID of booklist to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: BooklistResponse
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  customerId:
                    type: string
                  bookCount:
                    type: integer
                  tags:
                    type: array
                    items:
                      type: string
        "500":
          description: "Invalid input parameters"


    put:
      tags:
        - Booklists
      summary: Update the name of an existing booklist (UpdateBooklistLambda)
      parameters:
        - name: id
          in: path
          description: ID of booklist to retrieve
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                customerId:
                  type: string
    delete:
      tags:
        - Booklists
      summary: Remove a booklist (RemoveBooklistLambda)
      parameters:
        - name: id
          in: path
          description: ID of booklist to retrieve
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
      responses:
        "200":
          description: BooklistResponse
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  customerId:
                    type: string
                  bookCount:
                    type: integer
                  tags:
                    type: array
                    items:
                      type: string
        "500":
          description: "Invalid input parameters"

  /booklists/{id}/books:
    get:
      tags:
        - Books
      summary: Retrieves a list of all songs in a booklist (GetBooklistBooksLambda)
      operationId: getBooks
      parameters:
        - name: id
          in: path
          description: ID of booklist to return
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A booklist object
          content:
            application/json:
              schema:
                type: object
                properties:
                  booklist:
                    type: array
                    items:
                      properties:
                        asin:
                          type: string
                        title:
                          type: string
                        author:
                          type: string
                        genre:
                          type: string
                        rating:
                          type: integer
                        comments:
                          type: string
                        currentlyReading:
                          type: boolean
                        percentComplete:
                          type: integer

    post:
      tags:
        - Books
      summary: Add a book to a booklist (AddBookToBooklistLambda)
      operationId: addBook
      parameters:
        - name: id
          in: path
          description: ID of booklist to return
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                asin:
                  type: string
                id:
                  type: string

      responses:
        "200":
          description: the book
          content:
            application/json:
              schema:
                type: object
                properties:
                  songList:
                    type: array
                    items:
                      properties:
                        asin:
                          type: string
                        title:
                          type: string
                        author:
                          type: string
                        genre:
                          type: string
                        rating:
                          type: integer
                        comments:
                          type: string
                        currentlyReading:
                          type: boolean
                        percentComplete:
                          type: integer

  /books/search:
    get:
      tags:
        - Books
      parameters:
        - name: q
          in: query
          description: Search term (name or asin)
          required: true
          schema:
            type: array
            items:
              type: string
      summary: Search for a book (SearchBooksLambda)
      responses:
        "200":
          description: A book object
          content:
            application/json:
              schema:
                type: object
                properties:
                  asin:
                    type: string
                  title:
                    type: string
                  author:
                    type: string
                  genre:
                    type: string
                  rating:
                    type: integer
                  comments:
                    type: string
                  currentlyReading:
                    type: boolean
                  percentComplete:
                    type: integer